<a href="https://colab.research.google.com/github/gauravpks/ml-repo/blob/master/Part%200%20-%20Welcome%20to%20Machine%20Learning%20A-Z/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic on NumPy--------------- Gaurav Prakash

## Arrays vs Lists

In Data Science NumPy Arrays hold the key to data managagement... and are similar to Python list 

In [19]:
import numpy as np

In [20]:
L = [1,2,3]

In [21]:
type(L)

list

In [22]:
A = np.array([1,2,3])

In [23]:
A

array([1, 2, 3])

In [24]:
type(A)

numpy.ndarray

In [25]:
for e in L:
  print(e)

1
2
3


In [26]:
for e in A:
  print(e)

1
2
3


In [27]:
L.append(4)

In [9]:
L

[1, 2, 3, 4]

In [30]:
A.append(4) 
# doesn't work. Generally speaking.. size of list can change but size of array is same. 

AttributeError: ignored

In [32]:
#another way to add
L + [5]

[1, 2, 3, 4, 5]

In [35]:
A + np.array([4])
#Adds to each element--called as broadcasting in Numpay.. Not legal in Mathemetics.. Cannot add two arrays of differen size
# Power of Vector 

array([5, 6, 7])

In [37]:
A + np.array([4,5,6])
#Addition of Vector 

array([5, 7, 9])

In [38]:
A + np.array([4,5]) # doesn't work WHy???? ..  '+' is intellegent in NumPy

ValueError: ignored

In [39]:
#Scaler Multiplication to Array
2 * A

array([2, 4, 6])

In [17]:
# to List--- List L repeted 2 times.. 
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [40]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [41]:
# If you want to achieve.. Add 3 in each element.. like other programming lanagauage
L2 = []
for e in L:
  L2.append(e + 3)

In [42]:
L2

[4, 5, 6, 7]

In [44]:
#List comprehension
L2 = [e + 3 for e in L]

In [46]:
L2**2 ##Does not work

TypeError: ignored

In [ ]:
L2

[4, 5, 6, 7]

In [47]:
#Square in list
L2 = []
for e in L:
  L2.append(e**2)

In [48]:
L2

[1, 4, 9, 16]

In [50]:
## Way easier in NumPy Array
A**2

array([1, 4, 9])

In [51]:
#If you apply function on NumPY.. it does for all element wise
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [52]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [53]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [55]:
#Hyperbolic tangenet -- Used a lot in Deep Learning..
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

List looks like array.. but is just a Data Structure.. But NumPy Array is designed all for Mathematical Purpose


---



---



## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [56]:
# Creating 2 Arrays
a = np.array([1,2])
b = np.array([3,4])

In [59]:
#Element Wise Multiplication & Ssum
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [60]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [62]:
a * b

array([3, 8])

In [63]:
np.sum(a * b)

11

In [64]:
(a * b).sum()

11

In [65]:
## Dedicated function
np.dot(a, b)

11

In [66]:
#Instance method
a.dot(b)

11

In [67]:
b.dot(a)

11

In [69]:
#New Versions of NumPay
a @ b

11



---


Alternate definision of dot product in Ainear Algebra


---



---



$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

We do not know the cosine.. but we know other values via which we can calculate cosine programatically


How to find the magnatude of a Vector?? Square root of the sum of squire of all the elements

In [72]:
#magnatude of Vector.. dot product sqrt
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [74]:
#Direct linear algebra function
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [75]:
##Cosin of an angle
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [76]:
cosangle

0.9838699100999074

In [78]:
## To Get the angle in radian
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [81]:
##How Fast is numpay compared to list
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 61.086750832408434


## Matrices

In [84]:
#Metrics as a list of list without NumPy
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [85]:
L[0]

[1, 2]

In [87]:
#Row  & Column
L[0][1]

2

In [88]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [89]:
A[0][1]

2

In [90]:
A[0,1]

2

In [95]:
#NumPy array getting powerful
A[:,0]

array([1, 3])

In [96]:
A.T

array([[1, 3],
       [2, 4]])

In [97]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [99]:
## NumPy knows what your list contains.. and take list and returns a NumPy array.. No conversion required
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [100]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [102]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: ignored

In [103]:
#Getting Determinat
np.linalg.det(A)

-2.0000000000000004

In [ ]:
#Inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [104]:
#Multiply back.. to get an identity matrix.. not exactly 1 or -1.. as computer has limitation and usings some also
#to be careful
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [106]:
#Diagnol
np.diag(A)

array([1, 4])

In [109]:
#On a vector... Overloaded Function.. 
np.diag([1, 4])

array([[1, 0],
       [0, 4]])

## Solving Linear Systems

In [ ]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [ ]:
# don't do this
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random()

0.7581150038421872

In [ ]:
np.random.random((2, 3))

array([[0.03284802, 0.83250625, 0.2914984 ],
       [0.03998929, 0.85275735, 0.31078009]])

In [ ]:
np.random.randn(2, 3)

array([[ 0.97730916,  0.05594193, -2.46231718],
       [ 0.75246035, -1.46678342, -0.97568316]])

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

0.0008930280270368496

In [ ]:
np.mean(R)

In [ ]:
R.var()

1.0276856891466102

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0)

array([-0.00671182, -0.0086458 , -0.01834377])

In [ ]:
R.mean(axis=1).shape

(10000,)

In [ ]:
np.cov(R).shape

(10000, 10000)

In [ ]:
np.cov(R.T)

array([[ 0.98396137,  0.00432999,  0.01031152],
       [ 0.00432999,  0.99723915, -0.004402  ],
       [ 0.01031152, -0.004402  ,  0.99895114]])

In [ ]:
np.cov(R, rowvar=False)

array([[ 0.98396137,  0.00432999,  0.01031152],
       [ 0.00432999,  0.99723915, -0.004402  ],
       [ 0.01031152, -0.004402  ,  0.99895114]])

In [ ]:
np.random.randint(0, 10, size=(3, 3))

array([[6, 1, 2],
       [9, 7, 8],
       [4, 8, 1]])

In [ ]:
np.random.choice(10, size=(3, 3))

array([[3, 2, 5],
       [7, 8, 4],
       [6, 4, 1]])